name: Delete U Folder
on:
  workflow_dispatch:
    inputs:
      officelocation:
        description: 'Enter office location'
        required: true
        type: string
      username:
        description: 'Enter the username'
        required: true
        type: string

jobs:
  delete_folder:
    runs-on: self-hosted
    steps:
      - name: Run PowerShell Script
        run: |          
          $officelocation = "${{ github.event.inputs.officelocation }}"
          $username = "${{ github.event.inputs.username }}"

          # Debug: Output parameters
          Write-Host "Office Location: $officelocation"
          Write-Host "Username: $username"

          # Run the target PowerShell script with parameters
          & "D:\Udrivedelete\Udrivedelete.ps1" -officelocation $officelocation -username $username
