name: Delete Users U Drive
run-name: ${{ github.actor }} is actioning ${{ github.event.inputs.ticketID }}

on:
  workflow_dispatch:
    inputs:
      officelocation:
        description: 'Please enter office location'
        required: true
        type: string
      username:
        description: 'Please enter the first initial and last name of the user whose U: drive should be deleted'
        required: true
        type: string
      ticketID:
        description: 'Please enter the Jira ticket number'
        required: true
        type: string

jobs:
  delete_folder:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script Remotely
        shell: pwsh
        run: |
          # Get inputs from GitHub event
          $officelocation = "${{ github.event.inputs.officelocation }}"
          $username = "${{ github.event.inputs.username }}"
          
          # Execute the remote script on the target server
          Invoke-Command -ComputerName "psvau4wimg001.cmc.local" -ScriptBlock {
              param ($officelocation, $username)
              
              # Path to the PowerShell script on the remote machine
              $scriptPath = "C:\Users\adm-clucas\Udrivedelete\Udrivedelete.ps1"

              # Check if the script exists
              if (Test-Path $scriptPath) {
                  # Execute the script
                  & $scriptPath -officelocation $officelocation -username $username
              } else {
                  Write-Error "Script not found at $scriptPath"
              }
          } -ArgumentList $officelocation, $username
